/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HOOTToken } from "./HOOTToken";
export type { QFIToken } from "./QFIToken";
export type { StakingRewards } from "./StakingRewards";
